# Generated by Django 3.2.4 on 2021-06-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowhistory',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrowhistory',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
