# Generated by Django 3.2.4 on 2021-06-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210610_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowhistory',
            name='is_returned',
        ),
        migrations.RemoveField(
            model_name='borrowhistory',
            name='return_date',
        ),
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowhistory',
            name='returned_date',
            field=models.DateTimeField(null=True),
        ),
    ]
